server:
  port: 10012

spring:
  profiles:
    active: dev
  application:
    name: alive-gateway
  redis:
    host: 47.96.89.84
    port: 6379
    database: 2
  cloud:
    gateway:
      routes:
      - id: service01
        uri: lb://ALIVE-SERVICE-01
        predicates:
          - Path=/**
#        filters:
#        - name: RequestRateLimiter
#          args:
#            key-resolver: "#{@hostAddrKeyResolver}"
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10011/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug